export const SET_USER = "SET_USER";
export const SET_AUTH = "SET_AUTH";
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_SALE_WATCH = "ADD_TO_SALE_WATCH";
export const SET_NOTIFICATION_COUNT = "SET_NOTIFICATION_COUNT";
